services:
  bucko-web:
    build:
      target: development
    container_name: bucko-web-dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
